### ISSUE TITLE
Can all translations (and glosses) be expected to be in English?

### ISSUE THREAD

**Issue by xrotwang** [langsci/imtvault#3]
CLDF examples can specify the meta language explicitly. So if we knew that's always English, we could make this clear.

**Comment by Glottotopia** [comment]
It is English in maybe 95% of the cases, but it could be French or German as well. We can probably infer this from the book language. Book 27 is in French, so the translations will be in French as well etc. There is one book with several metalanguages (https://langsci-press.org/catalog/book/286), but I think it does not have any interlinear examples.

**Comment by Glottotopia** [comment]
now also with correct metalanguage for example glosses
