### ISSUE TITLE
Do LSP books use standard markup for a list of gloss abbreviations?

### ISSUE THREAD

**Issue by xrotwang** [langsci/imtvault#4]
If so, it may be worthwhile trying to parse this as well. The [LGR](https://www.eva.mpg.de/lingua/resources/glossing-rules.php) have this semi-standard way of including definitions of abbreviations as comma-separated key-value-pairs listed after the translation, so the relevant definitions could be included in individual examples.

This may be particularly useful in cases where LGT standard abbreviations have been re-defined in a book.

**Comment by Glottotopia** [comment]
There is an implicit standard for the abbreviation lists. This is not enforced, but should be followed in about 90% of the cases. 

In a former version of the parser, only those terms in small caps which matched an LGR abbreviation were retained for the category list. The assumption is that authors will not redefine LGR abbreviations (or that editors will not allow this to pass). But it was decided that non-standard abbreviations might be useful as well, even if they can have differing meanings between authors.

The more fundamental question is to what extent imtvault has as its mission to replicate the latex setup with all `\newcommand{}`s etc, i.e. in how far it is feasible and/or  desirable to parse LaTeX files other than the chapters themselves to retrieve better information. Related is the question to what extent imtvault will vouch for the correctness of the information. Currently, it only asserts "This string in the IMT-line was in smallcaps. Over to you". If we do some matching/normalization/unification, this can create the false expectation that everything is carefully curated.

**Comment by xrotwang** [comment]
Yes, I think expectations must be managed carefully here. But I also think that
1. even the status quo is already quite good (according to what can be checked automatically)
2. there are ways to transparently correct things (either in the books themselves, or by "errata-fixes" in [cldfbench's `etc/` directory](https://github.com/cldf/cldfbench/#overview)).

So if this set gets public exposure and has a way to incorporate feedback, I'd say it is on track to being "carefully curated".

**Comment by Glottotopia** [comment]
I could possibly provide something like 
```
{'categories' : [('acc', None), ('dat', None), ('frust', "Frustrative"), ...]}
```
The assumption would be that all categories with `None` get their basic LGR value if it exists. 

I could also fill in that LGR value, but that would be interpretation. 

A conceptual problem is that people use IMPERF, IMPF, IMPV, IPFV, IPFCT for 'imperfective'. We can get this information from the abbreviation list, but it is unclear to what extent imperfective of author A can be equated with imperfective of author B. Currently, the UI only gives the abbreviations ("Here is a string: ..."). If we match IMPERF, IMPF, IMPV, IPFV, IPFCT, we move away from the string representation and say: "Here is an object: X", where X has some attributes `original_abbrev` and  `normalized_abbrev` or similar. 

Maybe an extra field should be created for to store information which includes interpretations beyond "here is a string".

**Comment by xrotwang** [comment]
I think one big advantage of the situation here is that each example has transparent provenance, i.e. we always know who the author is. So I wouldn't change gloss abbreviations (other than the change from TeX command to proper uppercase abbreviation), but leave this for downstream processing. Once the example is fully parse-able (including its source), merging categories is easy to do - and can be left to pre-processing before any specific analysis.

**Comment by Glottotopia** [comment]
There is also a dictionary `abbrkey` for chapters from which the table with the abbreviations could be retrieved.
